# Generated by Django 4.2.1 on 2023-06-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_order_createdat_alter_order_isdelivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
